default_profile = "default"

[profiles.default]
user_id = "@user:matrix.org"
url = "https://matrix.org"

[settings]
default_room = "#fix-users:0x.badd.cafe"
external_edit_file_suffix = ".md"
log_level = "warn"
message_shortcode_display = false
open_command = ["my-open", "--file"]
reaction_display = true
reaction_shortcode_display = false
read_receipt_display = true
read_receipt_send = true
request_timeout = 10000
typing_notice_display = true
typing_notice_send = true
user_gutter_width = 30
username_display = "username"

[settings.image_preview]
protocol.type = "sixel"
size = { "width" = 66, "height" = 10 }

[settings.sort]
rooms = ["favorite", "lowpriority", "unread", "name"]
members = ["power", "id"]

[settings.users]
"@user:matrix.org" = { "name" = "John Doe", "color" = "magenta" }

[layout]
style = "config"

[[layout.tabs]]
window = "fix://dms"

[[layout.tabs]]
window = "fix://rooms"

[[layout.tabs]]
split = [
    { "window" = "#fix-users:0x.badd.cafe" },
    { "window" = "#fix-dev:0x.badd.cafe" }
]

[macros.insert]
"jj" = "<Esc>"

[macros."normal|visual"]
"V" = "<C-W>m"

[dirs]
cache = "/home/user/.cache/fix/"
logs = "/home/user/.local/share/fix/logs/"
downloads = "/home/user/Downloads/"
